/*
 * This file is generated by jOOQ.
 */
package co.selim.nemrut.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record FlywaySchemaHistory(
    Integer installedRank,
    String version,
    String description,
    String type,
    String script,
    Integer checksum,
    String installedBy,
    LocalDateTime installedOn,
    Integer executionTime,
    Boolean success
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
