/*
 * This file is generated by jOOQ.
 */
package co.selim.nemrut.jooq;


import co.selim.nemrut.jooq.tables.FlywaySchemaHistory;
import co.selim.nemrut.jooq.tables.Note;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.note</code>.
     */
    public static final Note NOTE = Note.NOTE;
}
