/*
 * This file is generated by jOOQ.
 */
package co.selim.nemrut.jooq;


import co.selim.nemrut.jooq.tables.Company;
import co.selim.nemrut.jooq.tables.FlywaySchemaHistory;
import co.selim.nemrut.jooq.tables.Role;
import co.selim.nemrut.jooq.tables.RolePermission;
import co.selim.nemrut.jooq.tables.Salary;
import co.selim.nemrut.jooq.tables.UserAccount;
import co.selim.nemrut.jooq.tables.UserRole;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = RolePermission.ROLE_PERMISSION;

    /**
     * The table <code>public.salary</code>.
     */
    public static final Salary SALARY = Salary.SALARY;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
